version: "3.9"

services:
  prefect:
    image: prefecthq/prefect:2-latest
    container_name: prefect
    command: prefect server start
    ports:
      - "4200:4200"   # Prefect UI
    environment:
      PREFECT_API_URL: http://prefect:4200/api
    volumes:
      - ./prefect-flows:/opt/prefect/flows

  # Your other services
  minio-aws:
    image: minio/minio
    ports:
      - "9001:9000"
    environment:
      MINIO_ROOT_USER: awsadmin
      MINIO_ROOT_PASSWORD: awspassword
    command: server /data

  minio-gcp:
    image: minio/minio
    ports:
      - "9002:9000"
    environment:
      MINIO_ROOT_USER: gcpadmin
      MINIO_ROOT_PASSWORD: gcppassword
    command: server /data

  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: invoicy
      POSTGRES_PASSWORD: invoicy
      POSTGRES_DB: invoicy
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"
      - "6334:6334"
